/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formulario;

import classes.UsuariosDAO;
import classes.Usuarios;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcelo.paula
 */
public class frmListagemUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListagemUsuarios
     */
    public frmListagemUsuarios() {
        initComponents();
        
        findAll();
    }
    
    public void findAll(){
        DefaultTableModel modelo = (DefaultTableModel) tbListagem.getModel();
        modelo.setNumRows(0);
        UsuariosDAO usu = new UsuariosDAO();
        
        for (Usuarios usuario : usu.findAll()) {
            modelo.addRow(new Object[] {
                usuario.getId(),
                usuario.getNome(),
                usuario.getEmail(),
                usuario.getLogin()
            });
        }
    }
    
    public void findByName(String nome){
        DefaultTableModel modelo = (DefaultTableModel) tbListagem.getModel();
        modelo.setNumRows(0);
        UsuariosDAO usu = new UsuariosDAO();
        
        for (Usuarios usuario : usu.findByName(nome)) {
            modelo.addRow(new Object[] {
                usuario.getId(),
                usuario.getNome(),
                usuario.getEmail(),
                usuario.getLogin()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListagem = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listagem de Usuários");
        setName("frmListagemUsuarios"); // NOI18N

        tbListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "E-Mail"
            }
        ));
        jScrollPane1.setViewportView(tbListagem);

        lblNome.setText("Informe seu nome para consulta");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtNome.getText().trim().isEmpty()){
            findAll();
        }else {
            findByName(txtNome.getText());
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tbListagem;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
